// @generated by protoc-gen-es v1.6.0 with parameter "target=ts"
// @generated from file proto/list-and-detail/list-dept.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message ListDeptRequest
 */
export class ListDeptRequest extends Message<ListDeptRequest> {
  constructor(data?: PartialMessage<ListDeptRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ListDeptRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListDeptRequest {
    return new ListDeptRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListDeptRequest {
    return new ListDeptRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListDeptRequest {
    return new ListDeptRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListDeptRequest | PlainMessage<ListDeptRequest> | undefined, b: ListDeptRequest | PlainMessage<ListDeptRequest> | undefined): boolean {
    return proto3.util.equals(ListDeptRequest, a, b);
  }
}

/**
 * @generated from message ListDeptResponse
 */
export class ListDeptResponse extends Message<ListDeptResponse> {
  /**
   * @generated from field: repeated ListDeptResponse.DeptData Depts = 1;
   */
  Depts: ListDeptResponse_DeptData[] = [];

  constructor(data?: PartialMessage<ListDeptResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ListDeptResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Depts", kind: "message", T: ListDeptResponse_DeptData, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListDeptResponse {
    return new ListDeptResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListDeptResponse {
    return new ListDeptResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListDeptResponse {
    return new ListDeptResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListDeptResponse | PlainMessage<ListDeptResponse> | undefined, b: ListDeptResponse | PlainMessage<ListDeptResponse> | undefined): boolean {
    return proto3.util.equals(ListDeptResponse, a, b);
  }
}

/**
 * @generated from message ListDeptResponse.DeptData
 */
export class ListDeptResponse_DeptData extends Message<ListDeptResponse_DeptData> {
  /**
   * @generated from field: int64 DeptID = 1;
   */
  DeptID = protoInt64.zero;

  /**
   * @generated from field: string Name = 2;
   */
  Name = "";

  constructor(data?: PartialMessage<ListDeptResponse_DeptData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ListDeptResponse.DeptData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "DeptID", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListDeptResponse_DeptData {
    return new ListDeptResponse_DeptData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListDeptResponse_DeptData {
    return new ListDeptResponse_DeptData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListDeptResponse_DeptData {
    return new ListDeptResponse_DeptData().fromJsonString(jsonString, options);
  }

  static equals(a: ListDeptResponse_DeptData | PlainMessage<ListDeptResponse_DeptData> | undefined, b: ListDeptResponse_DeptData | PlainMessage<ListDeptResponse_DeptData> | undefined): boolean {
    return proto3.util.equals(ListDeptResponse_DeptData, a, b);
  }
}

