// @generated by protoc-gen-es v1.6.0 with parameter "target=ts"
// @generated from file proto/authenticating/cm-authenticating.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message AuthenticateContentManagerRequest
 */
export class AuthenticateContentManagerRequest extends Message<AuthenticateContentManagerRequest> {
  /**
   * @generated from field: string Email = 1;
   */
  Email = "";

  /**
   * @generated from field: string Password = 2;
   */
  Password = "";

  constructor(data?: PartialMessage<AuthenticateContentManagerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "AuthenticateContentManagerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AuthenticateContentManagerRequest {
    return new AuthenticateContentManagerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AuthenticateContentManagerRequest {
    return new AuthenticateContentManagerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AuthenticateContentManagerRequest {
    return new AuthenticateContentManagerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AuthenticateContentManagerRequest | PlainMessage<AuthenticateContentManagerRequest> | undefined, b: AuthenticateContentManagerRequest | PlainMessage<AuthenticateContentManagerRequest> | undefined): boolean {
    return proto3.util.equals(AuthenticateContentManagerRequest, a, b);
  }
}

/**
 * @generated from message AuthenticateContentManagerResponse
 */
export class AuthenticateContentManagerResponse extends Message<AuthenticateContentManagerResponse> {
  /**
   * @generated from field: string Token = 1;
   */
  Token = "";

  /**
   * @generated from field: string Name = 2;
   */
  Name = "";

  /**
   * @generated from field: int64 ManagerID = 3;
   */
  ManagerID = protoInt64.zero;

  constructor(data?: PartialMessage<AuthenticateContentManagerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "AuthenticateContentManagerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "ManagerID", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AuthenticateContentManagerResponse {
    return new AuthenticateContentManagerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AuthenticateContentManagerResponse {
    return new AuthenticateContentManagerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AuthenticateContentManagerResponse {
    return new AuthenticateContentManagerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AuthenticateContentManagerResponse | PlainMessage<AuthenticateContentManagerResponse> | undefined, b: AuthenticateContentManagerResponse | PlainMessage<AuthenticateContentManagerResponse> | undefined): boolean {
    return proto3.util.equals(AuthenticateContentManagerResponse, a, b);
  }
}

/**
 * @generated from message LogoutContentManagerRequest
 */
export class LogoutContentManagerRequest extends Message<LogoutContentManagerRequest> {
  constructor(data?: PartialMessage<LogoutContentManagerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "LogoutContentManagerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogoutContentManagerRequest {
    return new LogoutContentManagerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogoutContentManagerRequest {
    return new LogoutContentManagerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogoutContentManagerRequest {
    return new LogoutContentManagerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: LogoutContentManagerRequest | PlainMessage<LogoutContentManagerRequest> | undefined, b: LogoutContentManagerRequest | PlainMessage<LogoutContentManagerRequest> | undefined): boolean {
    return proto3.util.equals(LogoutContentManagerRequest, a, b);
  }
}

/**
 * @generated from message RenewContentManagerSessionRequest
 */
export class RenewContentManagerSessionRequest extends Message<RenewContentManagerSessionRequest> {
  /**
   * @generated from field: string Token = 1;
   */
  Token = "";

  constructor(data?: PartialMessage<RenewContentManagerSessionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "RenewContentManagerSessionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RenewContentManagerSessionRequest {
    return new RenewContentManagerSessionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RenewContentManagerSessionRequest {
    return new RenewContentManagerSessionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RenewContentManagerSessionRequest {
    return new RenewContentManagerSessionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RenewContentManagerSessionRequest | PlainMessage<RenewContentManagerSessionRequest> | undefined, b: RenewContentManagerSessionRequest | PlainMessage<RenewContentManagerSessionRequest> | undefined): boolean {
    return proto3.util.equals(RenewContentManagerSessionRequest, a, b);
  }
}

