// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.21.12
// source: setting.proto

package scyna_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Setting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting) Reset() {
	*x = Setting{}
	mi := &file_setting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting) ProtoMessage() {}

func (x *Setting) ProtoReflect() protoreflect.Message {
	mi := &file_setting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting.ProtoReflect.Descriptor instead.
func (*Setting) Descriptor() ([]byte, []int) {
	return file_setting_proto_rawDescGZIP(), []int{0}
}

func (x *Setting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Setting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=Module,proto3" json:"Module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSettingRequest) Reset() {
	*x = ListSettingRequest{}
	mi := &file_setting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSettingRequest) ProtoMessage() {}

func (x *ListSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSettingRequest.ProtoReflect.Descriptor instead.
func (*ListSettingRequest) Descriptor() ([]byte, []int) {
	return file_setting_proto_rawDescGZIP(), []int{1}
}

func (x *ListSettingRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type ListSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Setting             `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSettingResponse) Reset() {
	*x = ListSettingResponse{}
	mi := &file_setting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSettingResponse) ProtoMessage() {}

func (x *ListSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSettingResponse.ProtoReflect.Descriptor instead.
func (*ListSettingResponse) Descriptor() ([]byte, []int) {
	return file_setting_proto_rawDescGZIP(), []int{2}
}

func (x *ListSettingResponse) GetItems() []*Setting {
	if x != nil {
		return x.Items
	}
	return nil
}

type WriteSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=Module,proto3" json:"Module,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSettingRequest) Reset() {
	*x = WriteSettingRequest{}
	mi := &file_setting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSettingRequest) ProtoMessage() {}

func (x *WriteSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSettingRequest.ProtoReflect.Descriptor instead.
func (*WriteSettingRequest) Descriptor() ([]byte, []int) {
	return file_setting_proto_rawDescGZIP(), []int{3}
}

func (x *WriteSettingRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *WriteSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteSettingRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=Module,proto3" json:"Module,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingRequest) Reset() {
	*x = UpdateSettingRequest{}
	mi := &file_setting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingRequest) ProtoMessage() {}

func (x *UpdateSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingRequest) Descriptor() ([]byte, []int) {
	return file_setting_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSettingRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *UpdateSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateSettingRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SettingUpdatedSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=Module,proto3" json:"Module,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingUpdatedSignal) Reset() {
	*x = SettingUpdatedSignal{}
	mi := &file_setting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingUpdatedSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingUpdatedSignal) ProtoMessage() {}

func (x *SettingUpdatedSignal) ProtoReflect() protoreflect.Message {
	mi := &file_setting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingUpdatedSignal.ProtoReflect.Descriptor instead.
func (*SettingUpdatedSignal) Descriptor() ([]byte, []int) {
	return file_setting_proto_rawDescGZIP(), []int{5}
}

func (x *SettingUpdatedSignal) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *SettingUpdatedSignal) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SettingUpdatedSignal) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ReadSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=Module,proto3" json:"Module,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSettingRequest) Reset() {
	*x = ReadSettingRequest{}
	mi := &file_setting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSettingRequest) ProtoMessage() {}

func (x *ReadSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSettingRequest.ProtoReflect.Descriptor instead.
func (*ReadSettingRequest) Descriptor() ([]byte, []int) {
	return file_setting_proto_rawDescGZIP(), []int{6}
}

func (x *ReadSettingRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ReadSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReadSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSettingResponse) Reset() {
	*x = ReadSettingResponse{}
	mi := &file_setting_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSettingResponse) ProtoMessage() {}

func (x *ReadSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setting_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSettingResponse.ProtoReflect.Descriptor instead.
func (*ReadSettingResponse) Descriptor() ([]byte, []int) {
	return file_setting_proto_rawDescGZIP(), []int{7}
}

func (x *ReadSettingResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RemoveSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=Module,proto3" json:"Module,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSettingRequest) Reset() {
	*x = RemoveSettingRequest{}
	mi := &file_setting_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSettingRequest) ProtoMessage() {}

func (x *RemoveSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setting_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSettingRequest.ProtoReflect.Descriptor instead.
func (*RemoveSettingRequest) Descriptor() ([]byte, []int) {
	return file_setting_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveSettingRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *RemoveSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SettingRemovedSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=Module,proto3" json:"Module,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingRemovedSignal) Reset() {
	*x = SettingRemovedSignal{}
	mi := &file_setting_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingRemovedSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingRemovedSignal) ProtoMessage() {}

func (x *SettingRemovedSignal) ProtoReflect() protoreflect.Message {
	mi := &file_setting_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingRemovedSignal.ProtoReflect.Descriptor instead.
func (*SettingRemovedSignal) Descriptor() ([]byte, []int) {
	return file_setting_proto_rawDescGZIP(), []int{9}
}

func (x *SettingRemovedSignal) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *SettingRemovedSignal) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_setting_proto protoreflect.FileDescriptor

var file_setting_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x73, 0x63, 0x79, 0x6e, 0x61, 0x22, 0x31, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2c, 0x0a, 0x12, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x3b, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x73, 0x63, 0x79, 0x6e, 0x61, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x05, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x55, 0x0a, 0x13, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x56, 0x0a, 0x14, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x56, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3e, 0x0a, 0x12, 0x52,
	0x65, 0x61, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x2b, 0x0a, 0x13, 0x52,
	0x65, 0x61, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x40, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x40, 0x0a, 0x14, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x42, 0x2f, 0x0a, 0x0b,
	0x73, 0x63, 0x79, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x02, 0x50, 0x01, 0x5a,
	0x0e, 0x2e, 0x2f, 0x3b, 0x73, 0x63, 0x79, 0x6e, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa,
	0x02, 0x0b, 0x73, 0x63, 0x79, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_setting_proto_rawDescOnce sync.Once
	file_setting_proto_rawDescData []byte
)

func file_setting_proto_rawDescGZIP() []byte {
	file_setting_proto_rawDescOnce.Do(func() {
		file_setting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_setting_proto_rawDesc), len(file_setting_proto_rawDesc)))
	})
	return file_setting_proto_rawDescData
}

var file_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_setting_proto_goTypes = []any{
	(*Setting)(nil),              // 0: scyna.Setting
	(*ListSettingRequest)(nil),   // 1: scyna.ListSettingRequest
	(*ListSettingResponse)(nil),  // 2: scyna.ListSettingResponse
	(*WriteSettingRequest)(nil),  // 3: scyna.WriteSettingRequest
	(*UpdateSettingRequest)(nil), // 4: scyna.UpdateSettingRequest
	(*SettingUpdatedSignal)(nil), // 5: scyna.SettingUpdatedSignal
	(*ReadSettingRequest)(nil),   // 6: scyna.ReadSettingRequest
	(*ReadSettingResponse)(nil),  // 7: scyna.ReadSettingResponse
	(*RemoveSettingRequest)(nil), // 8: scyna.RemoveSettingRequest
	(*SettingRemovedSignal)(nil), // 9: scyna.SettingRemovedSignal
}
var file_setting_proto_depIdxs = []int32{
	0, // 0: scyna.ListSettingResponse.Items:type_name -> scyna.Setting
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_setting_proto_init() }
func file_setting_proto_init() {
	if File_setting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_setting_proto_rawDesc), len(file_setting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_setting_proto_goTypes,
		DependencyIndexes: file_setting_proto_depIdxs,
		MessageInfos:      file_setting_proto_msgTypes,
	}.Build()
	File_setting_proto = out.File
	file_setting_proto_goTypes = nil
	file_setting_proto_depIdxs = nil
}
