// @generated by protoc-gen-es v1.6.0 with parameter "target=ts"
// @generated from file proto/editing/creating-commands.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message AddPostRequest
 */
export class AddPostRequest extends Message<AddPostRequest> {
  /**
   * @generated from field: string Title = 1;
   */
  Title = "";

  constructor(data?: PartialMessage<AddPostRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "AddPostRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddPostRequest {
    return new AddPostRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddPostRequest {
    return new AddPostRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddPostRequest {
    return new AddPostRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AddPostRequest | PlainMessage<AddPostRequest> | undefined, b: AddPostRequest | PlainMessage<AddPostRequest> | undefined): boolean {
    return proto3.util.equals(AddPostRequest, a, b);
  }
}

/**
 * @generated from message AddPostResponse
 */
export class AddPostResponse extends Message<AddPostResponse> {
  /**
   * @generated from field: int64 PostID = 1;
   */
  PostID = protoInt64.zero;

  constructor(data?: PartialMessage<AddPostResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "AddPostResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "PostID", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddPostResponse {
    return new AddPostResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddPostResponse {
    return new AddPostResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddPostResponse {
    return new AddPostResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AddPostResponse | PlainMessage<AddPostResponse> | undefined, b: AddPostResponse | PlainMessage<AddPostResponse> | undefined): boolean {
    return proto3.util.equals(AddPostResponse, a, b);
  }
}

