// @generated by protoc-gen-es v1.6.0 with parameter "target=ts"
// @generated from file proto/editing/creating-queries.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message ListEditingPostRequest
 */
export class ListEditingPostRequest extends Message<ListEditingPostRequest> {
  constructor(data?: PartialMessage<ListEditingPostRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ListEditingPostRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEditingPostRequest {
    return new ListEditingPostRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEditingPostRequest {
    return new ListEditingPostRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEditingPostRequest {
    return new ListEditingPostRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListEditingPostRequest | PlainMessage<ListEditingPostRequest> | undefined, b: ListEditingPostRequest | PlainMessage<ListEditingPostRequest> | undefined): boolean {
    return proto3.util.equals(ListEditingPostRequest, a, b);
  }
}

/**
 * @generated from message ListEditingPostResponse
 */
export class ListEditingPostResponse extends Message<ListEditingPostResponse> {
  /**
   * @generated from field: repeated ListEditingPostResponse.PostData Posts = 1;
   */
  Posts: ListEditingPostResponse_PostData[] = [];

  constructor(data?: PartialMessage<ListEditingPostResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ListEditingPostResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Posts", kind: "message", T: ListEditingPostResponse_PostData, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEditingPostResponse {
    return new ListEditingPostResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEditingPostResponse {
    return new ListEditingPostResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEditingPostResponse {
    return new ListEditingPostResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListEditingPostResponse | PlainMessage<ListEditingPostResponse> | undefined, b: ListEditingPostResponse | PlainMessage<ListEditingPostResponse> | undefined): boolean {
    return proto3.util.equals(ListEditingPostResponse, a, b);
  }
}

/**
 * @generated from message ListEditingPostResponse.PostData
 */
export class ListEditingPostResponse_PostData extends Message<ListEditingPostResponse_PostData> {
  /**
   * @generated from field: int64 PostID = 1;
   */
  PostID = protoInt64.zero;

  /**
   * @generated from field: string Title = 2;
   */
  Title = "";

  /**
   * @generated from field: google.protobuf.Timestamp CreatedAt = 3;
   */
  CreatedAt?: Timestamp;

  constructor(data?: PartialMessage<ListEditingPostResponse_PostData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ListEditingPostResponse.PostData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "PostID", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "Title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "CreatedAt", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListEditingPostResponse_PostData {
    return new ListEditingPostResponse_PostData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListEditingPostResponse_PostData {
    return new ListEditingPostResponse_PostData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListEditingPostResponse_PostData {
    return new ListEditingPostResponse_PostData().fromJsonString(jsonString, options);
  }

  static equals(a: ListEditingPostResponse_PostData | PlainMessage<ListEditingPostResponse_PostData> | undefined, b: ListEditingPostResponse_PostData | PlainMessage<ListEditingPostResponse_PostData> | undefined): boolean {
    return proto3.util.equals(ListEditingPostResponse_PostData, a, b);
  }
}

/**
 * @generated from message GetEditingPostRequest
 */
export class GetEditingPostRequest extends Message<GetEditingPostRequest> {
  /**
   * @generated from field: int64 PostID = 1;
   */
  PostID = protoInt64.zero;

  constructor(data?: PartialMessage<GetEditingPostRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "GetEditingPostRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "PostID", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEditingPostRequest {
    return new GetEditingPostRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEditingPostRequest {
    return new GetEditingPostRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEditingPostRequest {
    return new GetEditingPostRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEditingPostRequest | PlainMessage<GetEditingPostRequest> | undefined, b: GetEditingPostRequest | PlainMessage<GetEditingPostRequest> | undefined): boolean {
    return proto3.util.equals(GetEditingPostRequest, a, b);
  }
}

/**
 * @generated from message GetEditingPostResponse
 */
export class GetEditingPostResponse extends Message<GetEditingPostResponse> {
  /**
   * @generated from field: int64 PostID = 1;
   */
  PostID = protoInt64.zero;

  /**
   * @generated from field: string Title = 2;
   */
  Title = "";

  /**
   * @generated from field: string Content = 3;
   */
  Content = "";

  /**
   * @generated from field: string PreviewText = 4;
   */
  PreviewText = "";

  /**
   * @generated from field: uint64 PreviewImage = 5;
   */
  PreviewImage = protoInt64.zero;

  /**
   * @generated from field: repeated GetEditingPostResponse.ImageData Images = 6;
   */
  Images: GetEditingPostResponse_ImageData[] = [];

  constructor(data?: PartialMessage<GetEditingPostResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "GetEditingPostResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "PostID", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "Title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "PreviewText", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "PreviewImage", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "Images", kind: "message", T: GetEditingPostResponse_ImageData, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEditingPostResponse {
    return new GetEditingPostResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEditingPostResponse {
    return new GetEditingPostResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEditingPostResponse {
    return new GetEditingPostResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetEditingPostResponse | PlainMessage<GetEditingPostResponse> | undefined, b: GetEditingPostResponse | PlainMessage<GetEditingPostResponse> | undefined): boolean {
    return proto3.util.equals(GetEditingPostResponse, a, b);
  }
}

/**
 * @generated from message GetEditingPostResponse.ImageData
 */
export class GetEditingPostResponse_ImageData extends Message<GetEditingPostResponse_ImageData> {
  /**
   * @generated from field: uint64 ID = 1;
   */
  ID = protoInt64.zero;

  /**
   * @generated from field: string Url = 2;
   */
  Url = "";

  constructor(data?: PartialMessage<GetEditingPostResponse_ImageData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "GetEditingPostResponse.ImageData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ID", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "Url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEditingPostResponse_ImageData {
    return new GetEditingPostResponse_ImageData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEditingPostResponse_ImageData {
    return new GetEditingPostResponse_ImageData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEditingPostResponse_ImageData {
    return new GetEditingPostResponse_ImageData().fromJsonString(jsonString, options);
  }

  static equals(a: GetEditingPostResponse_ImageData | PlainMessage<GetEditingPostResponse_ImageData> | undefined, b: GetEditingPostResponse_ImageData | PlainMessage<GetEditingPostResponse_ImageData> | undefined): boolean {
    return proto3.util.equals(GetEditingPostResponse_ImageData, a, b);
  }
}

