// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

package scyna.proto;

public interface CreateStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scyna.CreateStreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Stream = 1;</code>
   * @return The stream.
   */
  java.lang.String getStream();
  /**
   * <code>string Stream = 1;</code>
   * @return The bytes for stream.
   */
  com.google.protobuf.ByteString
      getStreamBytes();
}
