// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

package scyna.proto;

public interface CreateConsumerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scyna.CreateConsumerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Stream = 1;</code>
   * @return The stream.
   */
  java.lang.String getStream();
  /**
   * <code>string Stream = 1;</code>
   * @return The bytes for stream.
   */
  com.google.protobuf.ByteString
      getStreamBytes();

  /**
   * <code>string Consumer = 2;</code>
   * @return The consumer.
   */
  java.lang.String getConsumer();
  /**
   * <code>string Consumer = 2;</code>
   * @return The bytes for consumer.
   */
  com.google.protobuf.ByteString
      getConsumerBytes();
}
