// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

package scyna.proto;

/**
 * Protobuf type {@code scyna.CreateConsumerRequest}
 */
public final class CreateConsumerRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:scyna.CreateConsumerRequest)
    CreateConsumerRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateConsumerRequest.newBuilder() to construct.
  private CreateConsumerRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateConsumerRequest() {
    stream_ = "";
    consumer_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateConsumerRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return scyna.proto.Stream.internal_static_scyna_CreateConsumerRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return scyna.proto.Stream.internal_static_scyna_CreateConsumerRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            scyna.proto.CreateConsumerRequest.class, scyna.proto.CreateConsumerRequest.Builder.class);
  }

  public static final int STREAM_FIELD_NUMBER = 1;
  private volatile java.lang.Object stream_;
  /**
   * <code>string Stream = 1;</code>
   * @return The stream.
   */
  @java.lang.Override
  public java.lang.String getStream() {
    java.lang.Object ref = stream_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stream_ = s;
      return s;
    }
  }
  /**
   * <code>string Stream = 1;</code>
   * @return The bytes for stream.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStreamBytes() {
    java.lang.Object ref = stream_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stream_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONSUMER_FIELD_NUMBER = 2;
  private volatile java.lang.Object consumer_;
  /**
   * <code>string Consumer = 2;</code>
   * @return The consumer.
   */
  @java.lang.Override
  public java.lang.String getConsumer() {
    java.lang.Object ref = consumer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      consumer_ = s;
      return s;
    }
  }
  /**
   * <code>string Consumer = 2;</code>
   * @return The bytes for consumer.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConsumerBytes() {
    java.lang.Object ref = consumer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      consumer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static scyna.proto.CreateConsumerRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static scyna.proto.CreateConsumerRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static scyna.proto.CreateConsumerRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static scyna.proto.CreateConsumerRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static scyna.proto.CreateConsumerRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static scyna.proto.CreateConsumerRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static scyna.proto.CreateConsumerRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static scyna.proto.CreateConsumerRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static scyna.proto.CreateConsumerRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static scyna.proto.CreateConsumerRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static scyna.proto.CreateConsumerRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static scyna.proto.CreateConsumerRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(scyna.proto.CreateConsumerRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code scyna.CreateConsumerRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scyna.CreateConsumerRequest)
      scyna.proto.CreateConsumerRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return scyna.proto.Stream.internal_static_scyna_CreateConsumerRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return scyna.proto.Stream.internal_static_scyna_CreateConsumerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              scyna.proto.CreateConsumerRequest.class, scyna.proto.CreateConsumerRequest.Builder.class);
    }

    // Construct using scyna.proto.CreateConsumerRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      stream_ = "";

      consumer_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return scyna.proto.Stream.internal_static_scyna_CreateConsumerRequest_descriptor;
    }

    @java.lang.Override
    public scyna.proto.CreateConsumerRequest getDefaultInstanceForType() {
      return scyna.proto.CreateConsumerRequest.getDefaultInstance();
    }

    @java.lang.Override
    public scyna.proto.CreateConsumerRequest build() {
      scyna.proto.CreateConsumerRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public scyna.proto.CreateConsumerRequest buildPartial() {
      scyna.proto.CreateConsumerRequest result = new scyna.proto.CreateConsumerRequest(this);
      result.stream_ = stream_;
      result.consumer_ = consumer_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    private java.lang.Object stream_ = "";
    /**
     * <code>string Stream = 1;</code>
     * @return The stream.
     */
    public java.lang.String getStream() {
      java.lang.Object ref = stream_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stream_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Stream = 1;</code>
     * @return The bytes for stream.
     */
    public com.google.protobuf.ByteString
        getStreamBytes() {
      java.lang.Object ref = stream_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stream_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Stream = 1;</code>
     * @param value The stream to set.
     * @return This builder for chaining.
     */
    public Builder setStream(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stream_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Stream = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStream() {
      
      stream_ = getDefaultInstance().getStream();
      onChanged();
      return this;
    }
    /**
     * <code>string Stream = 1;</code>
     * @param value The bytes for stream to set.
     * @return This builder for chaining.
     */
    public Builder setStreamBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stream_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object consumer_ = "";
    /**
     * <code>string Consumer = 2;</code>
     * @return The consumer.
     */
    public java.lang.String getConsumer() {
      java.lang.Object ref = consumer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consumer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Consumer = 2;</code>
     * @return The bytes for consumer.
     */
    public com.google.protobuf.ByteString
        getConsumerBytes() {
      java.lang.Object ref = consumer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Consumer = 2;</code>
     * @param value The consumer to set.
     * @return This builder for chaining.
     */
    public Builder setConsumer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      consumer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Consumer = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConsumer() {
      
      consumer_ = getDefaultInstance().getConsumer();
      onChanged();
      return this;
    }
    /**
     * <code>string Consumer = 2;</code>
     * @param value The bytes for consumer to set.
     * @return This builder for chaining.
     */
    public Builder setConsumerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      consumer_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:scyna.CreateConsumerRequest)
  }

  // @@protoc_insertion_point(class_scope:scyna.CreateConsumerRequest)
  private static final scyna.proto.CreateConsumerRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new scyna.proto.CreateConsumerRequest();
  }

  public static scyna.proto.CreateConsumerRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateConsumerRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateConsumerRequest>() {
    @java.lang.Override
    public CreateConsumerRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateConsumerRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateConsumerRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public scyna.proto.CreateConsumerRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

