// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace.proto

package scyna.proto;

public interface EndpointDoneSignalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scyna.EndpointDoneSignal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 TraceID = 1;</code>
   * @return The traceID.
   */
  long getTraceID();

  /**
   * <code>int32 Status = 2;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string Response = 3;</code>
   * @return The response.
   */
  java.lang.String getResponse();
  /**
   * <code>string Response = 3;</code>
   * @return The bytes for response.
   */
  com.google.protobuf.ByteString
      getResponseBytes();

  /**
   * <code>string Request = 4;</code>
   * @return The request.
   */
  java.lang.String getRequest();
  /**
   * <code>string Request = 4;</code>
   * @return The bytes for request.
   */
  com.google.protobuf.ByteString
      getRequestBytes();

  /**
   * <code>uint64 SessionID = 5;</code>
   * @return The sessionID.
   */
  long getSessionID();
}
