// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session.proto

package scyna.proto;

public interface EndSessionSignalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scyna.EndSessionSignal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 ID = 1;</code>
   * @return The iD.
   */
  long getID();

  /**
   * <code>uint32 Code = 2;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string Module = 3;</code>
   * @return The module.
   */
  java.lang.String getModule();
  /**
   * <code>string Module = 3;</code>
   * @return The bytes for module.
   */
  com.google.protobuf.ByteString
      getModuleBytes();
}
