// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto

package scyna.proto;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scyna.Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string Code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string Message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string Message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int64 Trace = 3;</code>
   * @return The trace.
   */
  long getTrace();
}
