// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scyna.proto

package scyna.proto;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scyna.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 TraceID = 1;</code>
   * @return The traceID.
   */
  long getTraceID();

  /**
   * <code>bytes Body = 2;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
