// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace.proto

package scyna.proto;

public interface LogCreatedSignalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scyna.LogCreatedSignal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 Time = 1;</code>
   * @return The time.
   */
  long getTime();

  /**
   * <code>uint64 ID = 4;</code>
   * @return The iD.
   */
  long getID();

  /**
   * <code>uint64 SEQ = 5;</code>
   * @return The sEQ.
   */
  long getSEQ();

  /**
   * <code>string Text = 3;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string Text = 3;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>uint32 Level = 2;</code>
   * @return The level.
   */
  int getLevel();
}
