// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto

package scyna.proto;

public final class Stream {
  private Stream() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scyna_CreateStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scyna_CreateStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scyna_CreateConsumerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scyna_CreateConsumerRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014stream.proto\022\005scyna\"%\n\023CreateStreamReq" +
      "uest\022\016\n\006Stream\030\001 \001(\t\"9\n\025CreateConsumerRe" +
      "quest\022\016\n\006Stream\030\001 \001(\t\022\020\n\010Consumer\030\002 \001(\tB" +
      "/\n\013scyna.protoH\002P\001Z\016./;scyna_proto\252\002\013scy" +
      "na.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_scyna_CreateStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_scyna_CreateStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scyna_CreateStreamRequest_descriptor,
        new java.lang.String[] { "Stream", });
    internal_static_scyna_CreateConsumerRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_scyna_CreateConsumerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scyna_CreateConsumerRequest_descriptor,
        new java.lang.String[] { "Stream", "Consumer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
