package scyna_const

const KEYSPACE = "scyna2"
const BASEPATH = "/scyna2"

const (
	GEN_GET_ID_URL                       = BASEPATH + "/generator/id"
	GEN_GET_SN_URL                       = BASEPATH + "/generator/sn"
	SESSION_CREATE_URL                   = BASEPATH + "/session/create"
	SETTING_WRITE_URL                    = BASEPATH + "/setting/write"
	SETTING_UPDATE_URL                   = BASEPATH + "/setting/update"
	SETTING_LIST_URL                     = BASEPATH + "/setting/list"
	SETTING_READ_URL                     = BASEPATH + "/setting/read"
	SETTING_REMOVE_URL                   = BASEPATH + "/setting/remove"
	START_TASK_URL                       = BASEPATH + "/task/start"
	STOP_TASK_URL                        = BASEPATH + "/task/stop"
	AUTH_CREATE_URL                      = BASEPATH + "/auth/create"
	AUTH_GET_URL                         = BASEPATH + "/auth/get"
	AUTH_LOGOUT_URL                      = BASEPATH + "/auth/logout"
	MODULE_CREATE                        = BASEPATH + "/module/create"
	MODULE_LIST                          = BASEPATH + "/module/list"
	MODULE_UPDATE                        = BASEPATH + "/module/update"
	ALERT_ADD_CHANNEL                    = BASEPATH + "/alert/add-channel"
	ALERT_LIST_CHANNEL                   = BASEPATH + "/alert/list-channel"
	ALERT_REMOVE_CHANNEL                 = BASEPATH + "/alert/remove-channel"
	ALERT_CHANNEL_ADD_RECEIVE            = BASEPATH + "/alert/channel-add-receive"
	ALERT_CHANNEL_REMOVE_RECEIVE         = BASEPATH + "/alert/channel-remove-receive"
	START_SCHEDULE_HOUSEKEEPING          = BASEPATH + "/housekeeping/start-schedule"
	STOP_SCHEDULE_HOUSEKEEPING           = BASEPATH + "/housekeeping/stop-schedule"
	MANUAL_HOUSEKEEPING_LOG              = BASEPATH + "/housekeeping/request-clean-log"
	MANUAL_HOUSEKEEPING_TRACE            = BASEPATH + "/housekeeping/request-clean-trace"
	MANUAL_HOUSEKEEPING_ENDPOINT_TRACE   = BASEPATH + "/housekeeping/request-clean-endpoint-trace"
	MANUAL_HOUSEKEEPING_ENDPOINT_MONITOR = BASEPATH + "/housekeeping/request-clean-endpoint-monitor"
)

const (
	SESSION_KILL_CHANNEL   = KEYSPACE + ".session.kill."
	SESSION_UPDATE_CHANNEL = KEYSPACE + ".session.update"
	SESSION_END_CHANNEL    = KEYSPACE + ".session.end"
	LOG_CREATED_CHANNEL    = KEYSPACE + ".log"
	TRACE_CREATED_CHANNEL  = KEYSPACE + ".trace"
	TAG_CREATED_CHANNEL    = KEYSPACE + ".tag"
	ENDPOINT_DONE_CHANNEL  = KEYSPACE + ".tag.endpoint"
	SETTING_UPDATE_CHANNEL = KEYSPACE + ".setting.updated."
	SETTING_REMOVE_CHANNEL = KEYSPACE + ".setting.removed."
	APP_UPDATE_CHANNEL     = KEYSPACE + ".application.updated"
	CLIENT_UPDATE_CHANNEL  = KEYSPACE + ".client.updated"
	SETTING_KEY            = KEYSPACE + ".module.config"
	ALERT_CREATED          = KEYSPACE + ".alert.created"
)
