// @generated by protoc-gen-es v1.6.0 with parameter "target=ts"
// @generated from file proto/authenticating/authenticate.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message AuthenticateUserRequest
 */
export class AuthenticateUserRequest extends Message<AuthenticateUserRequest> {
  /**
   * @generated from field: string Email = 1;
   */
  Email = "";

  /**
   * @generated from field: string Password = 2;
   */
  Password = "";

  constructor(data?: PartialMessage<AuthenticateUserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "AuthenticateUserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AuthenticateUserRequest {
    return new AuthenticateUserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AuthenticateUserRequest {
    return new AuthenticateUserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AuthenticateUserRequest {
    return new AuthenticateUserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AuthenticateUserRequest | PlainMessage<AuthenticateUserRequest> | undefined, b: AuthenticateUserRequest | PlainMessage<AuthenticateUserRequest> | undefined): boolean {
    return proto3.util.equals(AuthenticateUserRequest, a, b);
  }
}

/**
 * @generated from message AuthenticateUserResponse
 */
export class AuthenticateUserResponse extends Message<AuthenticateUserResponse> {
  /**
   * @generated from field: string Token = 1;
   */
  Token = "";

  /**
   * @generated from field: string Name = 2;
   */
  Name = "";

  /**
   * @generated from field: int64 UserID = 3;
   */
  UserID = protoInt64.zero;

  constructor(data?: PartialMessage<AuthenticateUserResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "AuthenticateUserResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "UserID", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AuthenticateUserResponse {
    return new AuthenticateUserResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AuthenticateUserResponse {
    return new AuthenticateUserResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AuthenticateUserResponse {
    return new AuthenticateUserResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AuthenticateUserResponse | PlainMessage<AuthenticateUserResponse> | undefined, b: AuthenticateUserResponse | PlainMessage<AuthenticateUserResponse> | undefined): boolean {
    return proto3.util.equals(AuthenticateUserResponse, a, b);
  }
}

/**
 * @generated from message LogoutUserRequest
 */
export class LogoutUserRequest extends Message<LogoutUserRequest> {
  constructor(data?: PartialMessage<LogoutUserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "LogoutUserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogoutUserRequest {
    return new LogoutUserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogoutUserRequest {
    return new LogoutUserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogoutUserRequest {
    return new LogoutUserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: LogoutUserRequest | PlainMessage<LogoutUserRequest> | undefined, b: LogoutUserRequest | PlainMessage<LogoutUserRequest> | undefined): boolean {
    return proto3.util.equals(LogoutUserRequest, a, b);
  }
}

/**
 * @generated from message RenewUserSessionRequest
 */
export class RenewUserSessionRequest extends Message<RenewUserSessionRequest> {
  /**
   * @generated from field: string Token = 1;
   */
  Token = "";

  constructor(data?: PartialMessage<RenewUserSessionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "RenewUserSessionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RenewUserSessionRequest {
    return new RenewUserSessionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RenewUserSessionRequest {
    return new RenewUserSessionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RenewUserSessionRequest {
    return new RenewUserSessionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RenewUserSessionRequest | PlainMessage<RenewUserSessionRequest> | undefined, b: RenewUserSessionRequest | PlainMessage<RenewUserSessionRequest> | undefined): boolean {
    return proto3.util.equals(RenewUserSessionRequest, a, b);
  }
}

