// @generated by protoc-gen-es v1.6.0 with parameter "target=ts"
// @generated from file proto/authenticating/websocket.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message ControlMessage
 */
export class ControlMessage extends Message<ControlMessage> {
  /**
   * PING, PONG, COMMAND
   *
   * @generated from field: string Type = 1;
   */
  Type = "";

  /**
   * @generated from field: bytes Data = 2;
   */
  Data = new Uint8Array(0);

  constructor(data?: PartialMessage<ControlMessage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ControlMessage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ControlMessage {
    return new ControlMessage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ControlMessage {
    return new ControlMessage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ControlMessage {
    return new ControlMessage().fromJsonString(jsonString, options);
  }

  static equals(a: ControlMessage | PlainMessage<ControlMessage> | undefined, b: ControlMessage | PlainMessage<ControlMessage> | undefined): boolean {
    return proto3.util.equals(ControlMessage, a, b);
  }
}

/**
 * @generated from message PushEvent
 */
export class PushEvent extends Message<PushEvent> {
  /**
   * @generated from field: string Channel = 1;
   */
  Channel = "";

  /**
   * @generated from field: bytes Data = 2;
   */
  Data = new Uint8Array(0);

  constructor(data?: PartialMessage<PushEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "PushEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Channel", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "Data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PushEvent {
    return new PushEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PushEvent {
    return new PushEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PushEvent {
    return new PushEvent().fromJsonString(jsonString, options);
  }

  static equals(a: PushEvent | PlainMessage<PushEvent> | undefined, b: PushEvent | PlainMessage<PushEvent> | undefined): boolean {
    return proto3.util.equals(PushEvent, a, b);
  }
}

