// @generated by protoc-gen-es v1.6.0 with parameter "target=ts"
// @generated from file proto/pagination-list/search-post.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message SearchPostRequest
 */
export class SearchPostRequest extends Message<SearchPostRequest> {
  /**
   * @generated from field: string Query = 1;
   */
  Query = "";

  constructor(data?: PartialMessage<SearchPostRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "SearchPostRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchPostRequest {
    return new SearchPostRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchPostRequest {
    return new SearchPostRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchPostRequest {
    return new SearchPostRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SearchPostRequest | PlainMessage<SearchPostRequest> | undefined, b: SearchPostRequest | PlainMessage<SearchPostRequest> | undefined): boolean {
    return proto3.util.equals(SearchPostRequest, a, b);
  }
}

/**
 * @generated from message SearchPostResponse
 */
export class SearchPostResponse extends Message<SearchPostResponse> {
  /**
   * @generated from field: repeated SearchPostResponse.PostData Posts = 1;
   */
  Posts: SearchPostResponse_PostData[] = [];

  constructor(data?: PartialMessage<SearchPostResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "SearchPostResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Posts", kind: "message", T: SearchPostResponse_PostData, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchPostResponse {
    return new SearchPostResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchPostResponse {
    return new SearchPostResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchPostResponse {
    return new SearchPostResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SearchPostResponse | PlainMessage<SearchPostResponse> | undefined, b: SearchPostResponse | PlainMessage<SearchPostResponse> | undefined): boolean {
    return proto3.util.equals(SearchPostResponse, a, b);
  }
}

/**
 * @generated from message SearchPostResponse.PostData
 */
export class SearchPostResponse_PostData extends Message<SearchPostResponse_PostData> {
  /**
   * @generated from field: int64 PostID = 1;
   */
  PostID = protoInt64.zero;

  /**
   * @generated from field: string Title = 2;
   */
  Title = "";

  /**
   * @generated from field: SearchPostResponse.PostData.AuthorData CreatedBy = 3;
   */
  CreatedBy?: SearchPostResponse_PostData_AuthorData;

  /**
   * @generated from field: google.protobuf.Timestamp PublishedAt = 4;
   */
  PublishedAt?: Timestamp;

  constructor(data?: PartialMessage<SearchPostResponse_PostData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "SearchPostResponse.PostData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "PostID", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "Title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "CreatedBy", kind: "message", T: SearchPostResponse_PostData_AuthorData },
    { no: 4, name: "PublishedAt", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchPostResponse_PostData {
    return new SearchPostResponse_PostData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchPostResponse_PostData {
    return new SearchPostResponse_PostData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchPostResponse_PostData {
    return new SearchPostResponse_PostData().fromJsonString(jsonString, options);
  }

  static equals(a: SearchPostResponse_PostData | PlainMessage<SearchPostResponse_PostData> | undefined, b: SearchPostResponse_PostData | PlainMessage<SearchPostResponse_PostData> | undefined): boolean {
    return proto3.util.equals(SearchPostResponse_PostData, a, b);
  }
}

/**
 * @generated from message SearchPostResponse.PostData.AuthorData
 */
export class SearchPostResponse_PostData_AuthorData extends Message<SearchPostResponse_PostData_AuthorData> {
  /**
   * @generated from field: int64 UserID = 1;
   */
  UserID = protoInt64.zero;

  /**
   * @generated from field: string Name = 2;
   */
  Name = "";

  constructor(data?: PartialMessage<SearchPostResponse_PostData_AuthorData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "SearchPostResponse.PostData.AuthorData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "UserID", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchPostResponse_PostData_AuthorData {
    return new SearchPostResponse_PostData_AuthorData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchPostResponse_PostData_AuthorData {
    return new SearchPostResponse_PostData_AuthorData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchPostResponse_PostData_AuthorData {
    return new SearchPostResponse_PostData_AuthorData().fromJsonString(jsonString, options);
  }

  static equals(a: SearchPostResponse_PostData_AuthorData | PlainMessage<SearchPostResponse_PostData_AuthorData> | undefined, b: SearchPostResponse_PostData_AuthorData | PlainMessage<SearchPostResponse_PostData_AuthorData> | undefined): boolean {
    return proto3.util.equals(SearchPostResponse_PostData_AuthorData, a, b);
  }
}

