// @generated by protoc-gen-es v1.6.0 with parameter "target=ts"
// @generated from file proto/list-and-detail/get-dept.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message GetDeptRequest
 */
export class GetDeptRequest extends Message<GetDeptRequest> {
  /**
   * @generated from field: int64 DeptID = 1;
   */
  DeptID = protoInt64.zero;

  constructor(data?: PartialMessage<GetDeptRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "GetDeptRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "DeptID", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetDeptRequest {
    return new GetDeptRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetDeptRequest {
    return new GetDeptRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetDeptRequest {
    return new GetDeptRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetDeptRequest | PlainMessage<GetDeptRequest> | undefined, b: GetDeptRequest | PlainMessage<GetDeptRequest> | undefined): boolean {
    return proto3.util.equals(GetDeptRequest, a, b);
  }
}

/**
 * @generated from message GetDeptResponse
 */
export class GetDeptResponse extends Message<GetDeptResponse> {
  /**
   * @generated from field: int64 DeptID = 1;
   */
  DeptID = protoInt64.zero;

  /**
   * @generated from field: string Name = 2;
   */
  Name = "";

  /**
   * @generated from field: string Description = 3;
   */
  Description = "";

  /**
   * @generated from field: string Location = 4;
   */
  Location = "";

  constructor(data?: PartialMessage<GetDeptResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "GetDeptResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "DeptID", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "Description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "Location", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetDeptResponse {
    return new GetDeptResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetDeptResponse {
    return new GetDeptResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetDeptResponse {
    return new GetDeptResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetDeptResponse | PlainMessage<GetDeptResponse> | undefined, b: GetDeptResponse | PlainMessage<GetDeptResponse> | undefined): boolean {
    return proto3.util.equals(GetDeptResponse, a, b);
  }
}

