// @generated by protoc-gen-es v1.6.0 with parameter "target=ts"
// @generated from file proto/pagination-list/list-post.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message ListPostRequest
 */
export class ListPostRequest extends Message<ListPostRequest> {
  /**
   * @generated from field: bytes Position = 1;
   */
  Position = new Uint8Array(0);

  /**
   * @generated from field: int32 Count = 2;
   */
  Count = 0;

  constructor(data?: PartialMessage<ListPostRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ListPostRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Position", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "Count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPostRequest {
    return new ListPostRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPostRequest {
    return new ListPostRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPostRequest {
    return new ListPostRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListPostRequest | PlainMessage<ListPostRequest> | undefined, b: ListPostRequest | PlainMessage<ListPostRequest> | undefined): boolean {
    return proto3.util.equals(ListPostRequest, a, b);
  }
}

/**
 * @generated from message ListPostResponse
 */
export class ListPostResponse extends Message<ListPostResponse> {
  /**
   * @generated from field: repeated ListPostResponse.PostData Posts = 1;
   */
  Posts: ListPostResponse_PostData[] = [];

  /**
   * @generated from field: bytes LastPosition = 2;
   */
  LastPosition = new Uint8Array(0);

  constructor(data?: PartialMessage<ListPostResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ListPostResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Posts", kind: "message", T: ListPostResponse_PostData, repeated: true },
    { no: 2, name: "LastPosition", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPostResponse {
    return new ListPostResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPostResponse {
    return new ListPostResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPostResponse {
    return new ListPostResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListPostResponse | PlainMessage<ListPostResponse> | undefined, b: ListPostResponse | PlainMessage<ListPostResponse> | undefined): boolean {
    return proto3.util.equals(ListPostResponse, a, b);
  }
}

/**
 * @generated from message ListPostResponse.PostData
 */
export class ListPostResponse_PostData extends Message<ListPostResponse_PostData> {
  /**
   * @generated from field: int64 PostID = 1;
   */
  PostID = protoInt64.zero;

  /**
   * @generated from field: string Title = 2;
   */
  Title = "";

  /**
   * @generated from field: ListPostResponse.PostData.AuthorData CreatedBy = 3;
   */
  CreatedBy?: ListPostResponse_PostData_AuthorData;

  /**
   * @generated from field: google.protobuf.Timestamp PublishedAt = 4;
   */
  PublishedAt?: Timestamp;

  constructor(data?: PartialMessage<ListPostResponse_PostData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ListPostResponse.PostData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "PostID", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "Title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "CreatedBy", kind: "message", T: ListPostResponse_PostData_AuthorData },
    { no: 4, name: "PublishedAt", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPostResponse_PostData {
    return new ListPostResponse_PostData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPostResponse_PostData {
    return new ListPostResponse_PostData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPostResponse_PostData {
    return new ListPostResponse_PostData().fromJsonString(jsonString, options);
  }

  static equals(a: ListPostResponse_PostData | PlainMessage<ListPostResponse_PostData> | undefined, b: ListPostResponse_PostData | PlainMessage<ListPostResponse_PostData> | undefined): boolean {
    return proto3.util.equals(ListPostResponse_PostData, a, b);
  }
}

/**
 * @generated from message ListPostResponse.PostData.AuthorData
 */
export class ListPostResponse_PostData_AuthorData extends Message<ListPostResponse_PostData_AuthorData> {
  /**
   * @generated from field: int64 UserID = 1;
   */
  UserID = protoInt64.zero;

  /**
   * @generated from field: string Name = 2;
   */
  Name = "";

  constructor(data?: PartialMessage<ListPostResponse_PostData_AuthorData>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ListPostResponse.PostData.AuthorData";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "UserID", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "Name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPostResponse_PostData_AuthorData {
    return new ListPostResponse_PostData_AuthorData().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPostResponse_PostData_AuthorData {
    return new ListPostResponse_PostData_AuthorData().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPostResponse_PostData_AuthorData {
    return new ListPostResponse_PostData_AuthorData().fromJsonString(jsonString, options);
  }

  static equals(a: ListPostResponse_PostData_AuthorData | PlainMessage<ListPostResponse_PostData_AuthorData> | undefined, b: ListPostResponse_PostData_AuthorData | PlainMessage<ListPostResponse_PostData_AuthorData> | undefined): boolean {
    return proto3.util.equals(ListPostResponse_PostData_AuthorData, a, b);
  }
}

